version: '3'

networks:
  back:
  
services:
  homecolis-api:
    image: homecolis-api:latest
    environment:
      - NODE_ENV=development
      - PORT=8080
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_USER=yolo
      - MONGO_PASSWORD=123456
    ports:
      - 80:8080
    networks:
      - back
    depends_on:
      - db
      
  db:
    image: aashreys/mongo-auth:latest
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=root
      - MONGODB_ADMIN_PASS=123456
      - MONGODB_APPLICATION_DATABASE=test
      - MONGODB_APPLICATION_USER=yolo
      - MONGODB_APPLICATION_PASS=123456
    volumes:
      - ./data-db:/data/db
    networks:
      - back
